# Config values
DATASET_PATH = 'reviews_cellphones.json'
MAX_REVIEW_LENGTH = 200
TOP_WORDS = 500
EMBEDDING_VECTOR_LENGTH = 32
MEMORY_UNITS = 50
NB_EPOCHS = 20
BATCH_SIZE = 32
DROPOUT = 0.2

SAVE_MODEL = True