# Config values
DATASET_PATH = 'reviews_cellphones.json'
MAX_REVIEW_LENGTH = 200
TOP_WORDS = 500
EMBEDDING_VECTOR_LENGTH = 32
MEMORY_UNITS = 100
NB_EPOCHS = 35
BATCH_SIZE = 64
DROPOUT = 0.6

SAVE_MODEL = True