# Config values
DATASET_PATH = 'reviews_cellphones.json'
MAX_REVIEW_LENGTH = 200
TOP_WORDS = 5000
EMBEDDING_VECTOR_LENGTH = 32
MEMORY_UNITS = 100
NB_EPOCHS = 10
BATCH_SIZE = 64
DROPOUT = 0.8

SAVE_MODEL = False